export const vaccines = {
  "AE": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "AF": {"most travelers": ["Hepatitis A", "Typhoid", "Polio"], "some travelers": ["Hepatitis B", "Cholera", "Malaria", "Rabies", "Yellow Fever"]},
  "AL": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies", "Yellow Fever"]},
  "AM": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies"]},
  "AR": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Yellow Fever"]},
  "AU": {"some travelers": ["Hepatitis A", "Hepatitis B", "Japanese Encephalitis", "Yellow Fever"]},
  "AW": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "BD": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Japanese Encephalitis", "Malaria", "Rabies", "Yellow Fever"]},
  "BO": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria"]},
  "BR": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Yellow Fever", "Hepatitis B", "Malaria", "Rabies"]},
  "BW": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "BZ": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies", "Yellow Fever", "Malaria"]},
  "CL": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "CN": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Japanese Encephalitis", "Polio", "Rabies", "Yellow Fever", "Malaria"]},
  "CO": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "CR": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies"]},
  "CU": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "CZ": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies"]},
  "DE": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "DK": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "EC": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "EG": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "ES": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "ET": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Malaria", "Meningitis", "Polio", "Rabies", "Yellow Fever"]},
  "FJ": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Yellow Fever"]},
  "FR": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "GB": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "GE": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies"]},
  "GH": {"all travelers": ["Yellow Fever"], "most travelers": ["Hepatitis A", "Malaria", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Meningitis", "Rabies"]},
  "GR": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "GT": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "GU": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B"]},
  "HN": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "HR": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies"]},
  "IL": {"most travelers": ["Hepatitis A"], "some travelers": ["Hepatitis B", "Rabies", "Typhoid"]},
  "IN": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "IQ": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Rabies", "Yellow Fever"]},
  "IT": {"some travelers": ["Hepatitis A", "Hepatitis B", "Rabies"]},
  "JP": {"some travelers": ["Hepatitis A", "Hepatitis B", "Japanese Encephalitis", "Rabies"]},
  "KE": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Cholera", "Hepatitis B", "Meningitis", "Polio", "Rabies", "Yellow Fever"]},
  "KH": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Japanese Encephalitis", "Malaria", "Rabies", "Yellow Fever"]},
  "LB": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "MA": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "MN": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "MX": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies", "Malaria"]},
  "MY": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Cholera", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "NI": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Rabies"]},
  "NP": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "PH": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "PK": {"most travelers": ["Hepatitis A", "Typhoid", "Polio"], "some travelers": ["Hepatitis B", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "PY": {"most travelers": ["Hepatitis A", "Typhoid", "Polio"], "some travelers": ["Hepatitis B", "Malaria", "Rabies", "Yellow Fever"]},
  "TH": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Cholera", "Malaria", "Japanese Encephalitis", "Rabies", "Yellow Fever"]},
  "TR": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies"]},
  "UG": {"all travelers": ["Yellow Fever"], "most travelers": ["Hepatitis A", "Typhoid", "Malaria"], "some travelers": ["Cholera", "Meningitis", "Hepatitis B", "Rabies"]},
  "VE": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Rabies", "Malaria", "Yellow Fever"]},
  "VN": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Japanese Encephalitis", "Rabies"]},
  "ZA": {"most travelers": ["Hepatitis A", "Typhoid"], "some travelers": ["Hepatitis B", "Malaria", "Yellow Fever", "Rabies"]}
}